# Generated by Django 3.1 on 2020-09-08 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calstudentID', models.IntegerField(null=True)),
                ('is_iep', models.BooleanField(default=False, null=True)),
                ('on_reduced_lunch', models.BooleanField(default=False, null=True)),
                ('race', models.CharField(choices=[('american_indian_or_alaska_native', 'American Indian or Alaska Native'), ('asian', 'Asian'), ('black_or_african_american', 'Black of African American'), ('hispanic_or_latino', 'Hispanic or Latino'), ('native_hawaiian_or_pacific_islander', 'Native Hawaiin or Pacific Islander'), ('white', 'White')], max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
