# Generated by Django 3.1 on 2020-09-08 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='race',
            field=models.CharField(choices=[('american_indian_or_alaska_native', 'American Indian or Alaska Native'), ('asian', 'Asian'), ('black_or_african_american', 'Black of African American'), ('hispanic_or_latino', 'Hispanic or Latino'), ('native_hawaiian_or_pacific_islander', 'Native Hawaiin or Pacific Islander'), ('white', 'White')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('section', models.CharField(max_length=20, null=True)),
                ('term', models.CharField(max_length=10, null=True)),
                ('credit_hours', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('end_date', models.DateField(auto_now_add=True, null=True)),
                ('secondary_instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_teacher', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
