# Generated by Django 3.1 on 2020-09-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_student_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
