# Generated by Django 3.1 on 2020-09-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200914_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpa',
            name='gpa',
            field=models.FloatField(),
        ),
    ]
