# Generated by Django 3.1 on 2020-09-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200914_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpa',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
